### ISSUE TITLE
"Hello World" loops not working correctly

### ISSUE THREAD

**Issue by rdebath** [tomsik68/brainfuck.c#1]
Neither the full "Hello World" from Wikipedia nor the one below is running correctly.

``` brainfuck
>++++++++[<+++++++++>-]<.>>+>+>++>[-]+<[>[->+<<++++>]<<]>.+++++++..+++.>
->+++++++.<+[>[+>]>]<<<+++++++++++++++.>>.+++.------.--------.>>+.>++++.
```

**Comment by tomsik68** [comment]
Thanks for reporting the issue :) . This code you posted should now work just fine. The problem was, that the interpreter didn't skip the loop to the end in case the currently pointed char was 0.
